version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create cloud formation stack"
          command: |
            echo $ACCESS_KEY_ID
            aws configure set aws_access_key_id $ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGIONq
            aws cloudformation deploy \
            --template-file server_infra.yml \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --region us-east-1

workflows:
  my_workflow:
    jobs:
      - create_infrastructure