version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create cloud formation stack"
          command: |
            aws cloudformation deploy \
            --template-file infra_scripts/server_infra.yml \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --region us-east-1

  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["66:9b:95:14:af:ca:fe:1a:ae:5c:5f:b8:44:08:b2:5f"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main1.yml
      # - run:
      #     name: Clear AWS resources on fail
      #     when: on_fail
      #     command: |
      #       echo "Clearing already provisioned AWS resources"
      #       python3 -m pip install awscli
      #       aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
      #       echo "Job to delete AWS resources started"

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
      - configure_infrastructure